### ISSUE TITLE
Add music

### ISSUE THREAD

**Issue by le-cds** [le-cds/shootemdead#17]
Hard electric guitars are where it's at!

**Comment by b3z** [comment]
I recommend [this](https://soundcloud.com/anttu-janhunen/false-awakenings) as bg music. And [that one (ONiOn No DOg OuT ThE DOor)](https://www.youtube.com/watch?v=sHbvLOtwaOs&t=9s) as cover / menu theme song.

**Comment by le-cds** [comment]
> I recommend [this](https://soundcloud.com/anttu-janhunen/false-awakenings) as bg music. And [that one (ONiOn No DOg OuT ThE DOor)](https://www.youtube.com/watch?v=sHbvLOtwaOs&t=9s) as cover / menu theme song.

Epic... I have an idea about what to do with this... Stay tuned. For a while. Until I find the time to actually implement my idea... :D
