### ISSUE TITLE
itch.io doesn't work

### ISSUE THREAD

**Issue by b3z** [le-cds/shootemdead#26]
![image](https://user-images.githubusercontent.com/47346598/74733908-9e4c9580-524d-11ea-9026-911bbddce91e.png)

**Comment by le-cds** [comment]
Oh noes!

Which browser on which operating system did you try to play it with?

**Comment by b3z** [comment]
Safari Version 13.0.1 (15608.2.11.1.1)
macOS Catalina 10.15 Beta (19A558d)
